- id: csquotes
  name: All quotation marks should use csquotes
  description: Ensure the use of LaTeX csquotes and prohibits manual quotation marks.
  entry: "``.*''"
  language: pygrep
  files: \.tex$
- id: cleveref-capitalization
  name: Ensure the correct usage of \cref
  description: Ensure that \Cref at a sentence start is capitalized and nowhere else in the sentence.
  entry: "^((\\s*\\\\cref)|[^%\\s]+\\\\Cref).*$"
  language: pygrep
  files: \.tex$
- id: tilde-cite
  name: Each \cite needs a ~
  description: Line breaks should never occur before the citation, thus they need to be protected with the ~.
  entry: "[^~]\\\\cite"
  language: pygrep
  files: \.tex$
- id: american-eg-ie
  name: US English requires a comma after "e.g." and "i.e."
  description: US English requires a comma after "e.g." and "i.e."
  entry: "((e\\.g\\.)|(i\\.e\\.))[^,]"
  language: pygrep
  files: \.tex$
